//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 */
public class CodeGeneration implements GJVisitor<String, String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if (n.present()) {
         String _ret = null;
         int _count = 0;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            e.nextElement().accept(this, argu);
            _count++;
         }
         return _ret;
      } else
         return null;
   }

   public String visit(NodeOptional n, String argu) {
      if (n.present())
         return n.node.accept(this, argu);
      else
         return null;
   }

   public String visit(NodeSequence n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) {
      return null;
   }

   public Map<String, LivenessAnalysis.ProcedureIntervals> procedureIntervals;
   public Map<String, Map<Integer, Map<String, String>>> procAllocationTimeline;
   Map<String, Integer> procStackSlots;
   String currProcedure = null;
   public int currPos = 1;

   public CodeGeneration(Map<String, LivenessAnalysis.ProcedureIntervals> procedureIntervals,
         Map<String, Map<Integer, Map<String, String>>> procAllocationTimeline, Map<String, Integer> procStackSlots) {
      this.procedureIntervals = procedureIntervals;
      this.procAllocationTimeline = procAllocationTimeline;
      this.procStackSlots = procStackSlots;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret = null;
      System.out.println(
            "MAIN [0][" + (procStackSlots.get("MAIN") + 10) + "][" + procedureIntervals.get("MAIN").maxCallArgs + "]");
      currProcedure = "MAIN";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      System.out.println("END");

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public String visit(Procedure n, String argu) {
      String _ret = null;
      currProcedure = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      System.out
            .println(currProcedure + "[" + id + "]["
                  + (procStackSlots.get(currProcedure) + 18 + Math.max(Integer.parseInt(id) - 4, 0))
                  + "][" + procedureIntervals.get(currProcedure).maxCallArgs + "]");
      currPos = 1;

      for (int i = 0; i < 8; i++) {
         System.out.println("ASTORE SPILLEDARG " + (i + 10) + " s" + i);
      }

      n.f4.accept(this, argu);

      for (int i = 0; i < 8; i++) {
         System.out.println("ALOAD s" + i + " SPILLEDARG " + (i + 10));
      }

      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    */
   public String visit(Stmt n, String argu) {
      currPos++;
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      System.out.println("NOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      System.out.println("ERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String lbl = n.f2.accept(this, argu);
      System.out.println("CJUMP " + reg + " " + lbl);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String lbl = n.f1.accept(this, argu);
      System.out.println("JUMP " + lbl);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public String visit(HStoreStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp1 = n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      String temp2 = n.f3.accept(this, argu);
      System.out.println("HSTORE " + temp1 + " " + id + " " + temp2);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp1 = n.f1.accept(this, argu);
      String temp2 = n.f2.accept(this, argu);
      String id = n.f3.accept(this, argu);
      System.out.println("HLOAD " + temp1 + " " + temp2 + " " + id);
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      System.out.println("MOVE " + temp + " " + exp);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      System.out.println("PRINT " + exp);
      return _ret;
   }

   /**
    * f0 -> Call()
    * | HAllocate()
    * | BinOp()
    * | SimpleExp()
    */
   public String visit(Exp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public String visit(StmtExp n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String retExp = n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      System.out.println("  MOVE v0 " + retExp);
      return "v0";
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public String visit(Call n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      for (int i = 0; i < 10; i++) {
         System.out.println("ASTORE SPILLEDARG " + i + " t" + i);
      }

      // Collect arguments
      List<String> args = new ArrayList<>();
      if (n.f3.present()) {
         for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            String temp = e.nextElement().accept(this, argu);
            args.add(temp);
         }
      }
      // Move first 4 args to a0-a3, rest go to passarg
      for (int i = 0; i < args.size(); i++) {
         if (i < 4) {
            System.out.println("  MOVE a" + i + " " + args.get(i));
         } else {
            System.out.println("  PASSARG " + (i - 4) + " " + args.get(i));
         }
      }

      n.f4.accept(this, argu);
      String result = "CALL " + exp;
      System.out.println(result);
      for (int i = 0; i < 10; i++) {
         System.out.println("ALOAD t" + i + " SPILLEDARG " + i);
      }
      return "v0";
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      String result = "HALLOCATE " + exp;
      return result;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      String op = n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      String result = op + " " + reg + " " + exp;
      return result;
   }

   /**
    * f0 -> "LE"
    * | "NE"
    * | "PLUS"
    * | "MINUS"
    * | "TIMES"
    * | "DIV"
    */
   public String visit(Operator n, String argu) {
      n.f0.accept(this, argu);
      String[] arr = { "LE", "NE", "PLUS", "MINUS", "TIMES", "DIV" };
      int x = n.f0.which;
      return arr[x];
   }

   /**
    * f0 -> Temp()
    * | IntegerLiteral()
    * | Label()
    */
   public String visit(SimpleExp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public String visit(Temp n, String argu) {
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      String reg = procAllocationTimeline.get(currProcedure).get(currPos).get("TEMP " + id);
      return reg;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Label n, String argu) {
      n.f0.accept(this, argu);
      String id = n.f0.toString();
      if (id.startsWith("L"))
         System.out.println(id);
      return n.f0.toString();
   }

}
