//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 */
public class CodeGeneration implements GJVisitor<String, String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if (n.present()) {
         String _ret = null;
         int _count = 0;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            e.nextElement().accept(this, argu);
            _count++;
         }
         return _ret;
      } else
         return null;
   }

   public String visit(NodeOptional n, String argu) {
      if (n.present())
         return n.node.accept(this, argu);
      else
         return null;
   }

   public String visit(NodeSequence n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) {
      return null;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String params = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String StackSpace = n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      String MaxParams = n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      System.out.println("\t.text");
      System.out.println("\t.globl main");
      System.out.println("main:");
      System.out.println("\tmove $fp, $sp");
      System.out.println("\tsw $ra, -4($fp)");
      System.out.println("\tsubu $sp, $sp, " + ((Integer.parseInt(StackSpace) + 1) * 4));
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      System.out.println("\taddu $sp, $sp, " + ((Integer.parseInt(StackSpace) + 1) * 4));
      System.out.println("\tlw $ra, -4($fp)");
      System.out.println("\tj $ra\n");
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);

      System.out.println("\t.text\n" + //
            "\t.globl _halloc\n" + //
            "\n" + //
            "_halloc:\n" + //
            "\tli $v0, 9\n" + //
            "\tsyscall\n" + //
            "\tj $ra\n" + //
            "\n" + //
            "\t.text\n" + //
            "\t.globl _print\n" + //
            "_print:\n" + //
            "\tli $v0, 1\n" + //
            "\tsyscall\n" + //
            "\tla $a0, newl\n" + //
            "\tli $v0, 4\n" + //
            "\tsyscall\n" + //
            "\tj $ra\n" + //
            "\n" + //
            "\t.data\n" + //
            "\t.align 0\n" + //
            "newl:\t.asciiz \"\\n" + //
            "\"\n" + //
            "\t.data\n" + //
            "\t.align 0\n" + //
            "str_er:\t.asciiz \"ERROR: abnormal termination\\n" + //
            "\"");
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, String argu) {
      for (Node node : n.f0.nodes) {
         NodeSequence pair = (NodeSequence) node;

         if (pair.elementAt(0) instanceof NodeOptional) {
            NodeOptional opt = (NodeOptional) pair.elementAt(0);
            if (opt.present()) {
               Label labelNode = (Label) opt.node;
               String label = labelNode.f0.toString();
               System.out.println(label + ":");
            }
         }

         pair.elementAt(1).accept(this, argu);
      }
      return null;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public String visit(Procedure n, String argu) {
      String _ret = null;
      String lbl = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String params = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String StackSpace = n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      String maxParams = n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      System.out.println("\t.text");
      System.out.println("\t.globl " + lbl);
      System.out.println(lbl + ":");
      System.out.println("\tsw $fp, -8($sp)");
      System.out.println("\tmove $fp, $sp");
      System.out.println("\tsw $ra, -4($fp)");
      System.out.println("\tsubu $sp, $sp, " + ((Integer.parseInt(StackSpace) + 2) * 4));

      n.f10.accept(this, argu);

      System.out.println("\taddu $sp, $sp, " + ((Integer.parseInt(StackSpace) + 2) * 4));
      System.out.println("\tlw $ra, -4($fp)");
      System.out.println("\tlw $fp, -8($sp)");
      System.out.println("\tj $ra\n");
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    * | ALoadStmt()
    * | AStoreStmt()
    * | PassArgStmt()
    * | CallStmt()
    */
   public String visit(Stmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      System.out.println("\tnop");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String lbl = n.f2.accept(this, argu);
      System.out.println("\tbeqz " + reg + " " + lbl);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String lbl = n.f1.accept(this, argu);
      System.out.println("\tb " + lbl);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public String visit(HStoreStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg1 = n.f1.accept(this, argu);
      String num = n.f2.accept(this, argu);
      String reg2 = n.f3.accept(this, argu);
      System.out.println("\tsw " + reg2 + ", " + num + "(" + reg1 + ")");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg1 = n.f1.accept(this, argu);
      String reg2 = n.f2.accept(this, argu);
      String num = n.f3.accept(this, argu);
      System.out.println("\tlw " + reg1 + ", " + num + "(" + reg2 + ")");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg1 = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
    if (exp.startsWith("$")) {
        // It's a register
        System.out.println("\tmove " + reg1 + ", " + exp);
    } else {
        try {
            // Try parsing as integer
            int value = Integer.parseInt(exp);
            System.out.println("\tli " + reg1 + ", " + value);
        } catch (NumberFormatException e) {
            // Otherwise, assume it's a label/string
            System.out.println("\tla " + reg1 + ", " + exp);
        }
    }
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      System.out.println("\tmove $a0, " + exp);
      System.out.println("\tjal _print");
      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public String visit(ALoadStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String arg = n.f2.accept(this, argu);
      System.out.println("\tlw " + reg + ", " + (Integer.parseInt(arg) * 4) + "($sp)");
      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public String visit(AStoreStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String num = n.f1.accept(this, argu);
      String reg = n.f2.accept(this, argu);
      System.out.println("\tsw " + reg + ", " + (Integer.parseInt(num) * 4) + "($sp)");
      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public String visit(PassArgStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String num = n.f1.accept(this, argu);
      String reg = n.f2.accept(this, argu);
      System.out.println("\tsw " + reg + ", " + ((Integer.parseInt(num) - 1) * 4) + "($sp)");
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public String visit(CallStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      System.out.println("\tjalr " + exp);
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    * | BinOp()
    * | SimpleExp()
    */
   public String visit(Exp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      System.out.println("\tmove $a0, " + exp);
      System.out.println("\tjal _halloc");
      return "$v0";
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      String op = n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);
      String opCode = switch (op) {
         case "PLUS" -> "add";
         case "MINUS" -> "sub";
         case "TIMES" -> "mul";
         case "DIV" -> "div";
         case "LE" -> "sle";
         case "NE" -> "sne";
         default -> "???";
      };

      System.out.println("\t" + opCode + " $v1, " + reg + ", " + exp);
      return "$v1";
   }

   /**
    * f0 -> "LE"
    * | "NE"
    * | "PLUS"
    * | "MINUS"
    * | "TIMES"
    * | "DIV"
    */
   public String visit(Operator n, String argu) {
      String op = n.f0.choice.toString();
      return op;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public String visit(SpilledArg n, String argu) {
      n.f0.accept(this, argu);
      String num = n.f1.accept(this, argu);
      return num;
   }

   /**
    * f0 -> Reg()
    * | IntegerLiteral()
    * | Label()
    */
   public String visit(SimpleExp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "a0"
    * | "a1"
    * | "a2"
    * | "a3"
    * | "t0"
    * | "t1"
    * | "t2"
    * | "t3"
    * | "t4"
    * | "t5"
    * | "t6"
    * | "t7"
    * | "s0"
    * | "s1"
    * | "s2"
    * | "s3"
    * | "s4"
    * | "s5"
    * | "s6"
    * | "s7"
    * | "t8"
    * | "t9"
    * | "v0"
    * | "v1"
    */
   public String visit(Reg n, String argu) {
      String reg = n.f0.choice.toString();
      return "$" + reg;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Label n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public String visit(SpillInfo n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    * | <NOTSPILLED>
    */
   public String visit(SpillStatus n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

}
