//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order. Your visitors may extend this class.
 */
public class CodeGeneration implements GJVisitor<String, String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if (n.present()) {
         String _ret = null;
         int _count = 0;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            e.nextElement().accept(this, argu);
            _count++;
         }
         return _ret;
      } else
         return null;
   }

   public String visit(NodeOptional n, String argu) {
      if (n.present())
         return n.node.accept(this, argu);
      else
         return null;
   }

   public String visit(NodeSequence n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) {
      return null;
   }

   public Map<String, LivenessAnalysis.ProcedureIntervals> procedureIntervals;
   public Map<String, Map<Integer, Map<String, String>>> procAllocationTimeline;
   Map<String, Integer> procStackSlots;
   String currProcedure = null;
   public int currPos = 1;

   public CodeGeneration(Map<String, LivenessAnalysis.ProcedureIntervals> procedureIntervals,
         Map<String, Map<Integer, Map<String, String>>> procAllocationTimeline, Map<String, Integer> procStackSlots) {
      this.procedureIntervals = procedureIntervals;
      this.procAllocationTimeline = procAllocationTimeline;
      this.procStackSlots = procStackSlots;
   }

   private String resolveStackLocation(String location) {
      if (location != null && location.startsWith("stack[")) {
         int start = location.indexOf('[') + 1;
         int end = location.indexOf(']');
         int slot = Integer.parseInt(location.substring(start, end));
         return "SPILLEDARG " + (slot + 18);
      }
      return location;
   }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret = null;
      System.out.println(
            "MAIN [0][" + (procStackSlots.get("MAIN") + 100) + "][" + procedureIntervals.get("MAIN").maxCallArgs + "]");
      currProcedure = "MAIN";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      System.out.println("END");

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, String argu) {
      for (Node node : n.f0.nodes) {
         NodeSequence pair = (NodeSequence) node;

         if (pair.elementAt(0) instanceof NodeOptional) {
            NodeOptional opt = (NodeOptional) pair.elementAt(0);
            if (opt.present()) {
               Label labelNode = (Label) opt.node;
               String label = labelNode.f0.toString();
               System.out.println(label);
            }
         }

         pair.elementAt(1).accept(this, argu);
      }
      return null;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public String visit(Procedure n, String argu) {
      String _ret = null;
      currProcedure = n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      System.out
            .println(currProcedure + "[" + id + "]["
                  + (1000 + procStackSlots.get(currProcedure) + 18 + Math.max(Integer.parseInt(id) - 4, 0))
                  + "][" + procedureIntervals.get(currProcedure).maxCallArgs + "]");
      currPos = 1;

      for (int i = 0; i < 8; i++) {
         System.out.println("ASTORE SPILLEDARG " + (i + 10) + " s" + i);
      }

      int numParams = Integer.parseInt(id);
      for (int i = 0; i < numParams && i < 4; i++) {
         String tempId = "TEMP " + i;
         String allocatedReg = procAllocationTimeline.get(currProcedure).get(currPos).get(tempId);
         if (allocatedReg != null) {
            if (allocatedReg.startsWith("stack[")) {
               String stackLoc = resolveStackLocation(allocatedReg);
               System.out.println("ALOAD " + allocatedReg + " " + stackLoc);
            } else {
               System.out.println("MOVE " + allocatedReg + " a" + i);
            }
         }
      }

      for (int i = 4; i < numParams; i++) {
         String tempId = "TEMP " + i;
         String allocatedReg = procAllocationTimeline.get(currProcedure).get(currPos).get(tempId);
         if (allocatedReg != null) {
            System.out.println("ALOAD " + allocatedReg + " SPILLEDARG " + (i - 4));
         }
      }

      n.f4.accept(this, argu);

      for (int i = 0; i < 8; i++) {
         System.out.println("ALOAD s" + i + " SPILLEDARG " + (i + 10));
      }

      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    */
   public String visit(Stmt n, String argu) {
      currPos++;
      String _ret = null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      System.out.println("NOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      System.out.println("ERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String lbl = n.f2.accept(this, argu);

      if (reg != null && reg.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(reg);
         System.out.println("ALOAD v1 " + stackLoc);
         reg = "v1";
      }

      System.out.println("CJUMP " + reg + " " + lbl);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String lbl = n.f1.accept(this, argu);
      System.out.println("JUMP " + lbl);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public String visit(HStoreStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp1 = n.f1.accept(this, argu);
      String id = n.f2.accept(this, argu);
      String temp2 = n.f3.accept(this, argu);

      String reg1 = temp1;
      String reg2 = temp2;

      if (temp1 != null && temp1.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(temp1);
         System.out.println("ALOAD v1 " + stackLoc);
         reg1 = "v1";
      }
      if (temp2 != null && temp2.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(temp2);
         System.out.println("ALOAD v0 " + stackLoc);
         reg2 = "v0";
      }

      System.out.println("HSTORE " + reg1 + " " + id + " " + reg2);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp1 = n.f1.accept(this, argu);
      String temp2 = n.f2.accept(this, argu);
      String id = n.f3.accept(this, argu);

      if (temp2 != null && temp2.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(temp2);
         System.out.println("ALOAD v1 " + stackLoc);
         temp2 = "v1";
      }

      String destReg = temp1;
      if (temp1 != null && temp1.startsWith("stack[")) {
         destReg = "v1";
      }

      System.out.println("HLOAD " + destReg + " " + temp2 + " " + id);

      if (temp1 != null && temp1.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(temp1);
         System.out.println("ASTORE " + stackLoc + " v1");
      }

      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String temp = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);

      if (exp != null && exp.contains("stack[")) {
         exp = resolveStackReferencesInExp(exp);
      }

      if (temp != null && temp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(temp);
         System.out.println("MOVE v1 " + exp);
         System.out.println("ASTORE " + stackLoc + " v1");
      } else {
         System.out.println("MOVE " + temp + " " + exp);
      }

      return _ret;
   }

   private String resolveStackReferencesInExp(String exp) {
      String[] parts = exp.split(" ");
      StringBuilder result = new StringBuilder();
      boolean hasStackRef = false;

      for (int i = 0; i < parts.length; i++) {
         if (parts[i].startsWith("stack[")) {
            String stackLoc = resolveStackLocation(parts[i]);
            if (!hasStackRef) {
               System.out.println("ALOAD v1 " + stackLoc);
               result.append("v1");
               hasStackRef = true;
            } else {
               System.out.println("ALOAD v0 " + stackLoc);
               result.append("v0");
            }
         } else {
            result.append(parts[i]);
         }

         if (i < parts.length - 1) {
            result.append(" ");
         }
      }

      return result.toString();
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      String _ret = null;
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      if (exp != null && exp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(exp);
         System.out.println("ALOAD v1 " + stackLoc);
         exp = "v1";
      }
      System.out.println("PRINT " + exp);
      return _ret;
   }

   /**
    * f0 -> Call()
    * | HAllocate()
    * | BinOp()
    * | SimpleExp()
    */
   public String visit(Exp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public String visit(StmtExp n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String retExp = n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      // Handle stack location
      if (retExp != null && retExp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(retExp);
         System.out.println("  ALOAD v0 " + stackLoc);
      } else {
         System.out.println("  MOVE v0 " + retExp);
      }

      return "v0";
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public String visit(Call n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      for (int i = 0; i < 10; i++) {
         System.out.println("ASTORE SPILLEDARG " + i + " t" + i);
      }

      List<String> args = new ArrayList<>();
      if (n.f3.present()) {
         for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            String temp = e.nextElement().accept(this, argu);
            args.add(temp);
         }
      }
      for (int i = 0; i < args.size(); i++) {
         String arg = args.get(i);

         if (arg != null && arg.startsWith("stack[")) {
            String stackLoc = resolveStackLocation(arg);
            System.out.println("  ALOAD v1 " + stackLoc);
            arg = "v1";
         }

         if (i < 4) {
            System.out.println("  MOVE a" + i + " " + arg);
         } else {
            System.out.println("  PASSARG " + (i - 4 + 1) + " " + arg);
         }
      }

      n.f4.accept(this, argu);

      String callTarget = exp;
      if (exp != null && exp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(exp);
         System.out.println("ALOAD v1 " + stackLoc);
         callTarget = "v1";
      }

      String result = "CALL " + callTarget;
      System.out.println(result);
      for (int i = 0; i < 10; i++) {
         System.out.println("ALOAD t" + i + " SPILLEDARG " + i);
      }
      return "v0";
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, String argu) {
      n.f0.accept(this, argu);
      String exp = n.f1.accept(this, argu);
      if (exp != null && exp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(exp);
         System.out.println("ALOAD v1 " + stackLoc);
         exp = "v1";
      }

      String result = "HALLOCATE " + exp;
      return result;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      String op = n.f0.accept(this, argu);
      String reg = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, argu);

      String actualReg = reg;
      String actualExp = exp;

      if (reg != null && reg.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(reg);
         System.out.println("ALOAD v1 " + stackLoc);
         actualReg = "v1";
      }
      if (exp != null && exp.startsWith("stack[")) {
         String stackLoc = resolveStackLocation(exp);
         System.out.println("ALOAD v0 " + stackLoc);
         actualExp = "v0";
      }

      String result = op + " " + actualReg + " " + actualExp;
      return result;
   }

   /**
    * f0 -> "LE"
    * | "NE"
    * | "PLUS"
    * | "MINUS"
    * | "TIMES"
    * | "DIV"
    */
   public String visit(Operator n, String argu) {
      n.f0.accept(this, argu);
      String[] arr = { "LE", "NE", "PLUS", "MINUS", "TIMES", "DIV" };
      int x = n.f0.which;
      return arr[x];
   }

   /**
    * f0 -> Temp()
    * | IntegerLiteral()
    * | Label()
    */
   public String visit(SimpleExp n, String argu) {
      String exp = n.f0.accept(this, argu);
      return exp;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public String visit(Temp n, String argu) {
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      String reg = procAllocationTimeline.get(currProcedure).get(currPos).get("TEMP " + id);
      return reg;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Label n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

}