//
// Generated by JTB 1.3.2
//

package visitor;

import syntaxtree.*;
import java.util.*;

/**
 * Loop-aware liveness analysis that extends live ranges through loops
 */
public class LivenessAnalysis implements GJVisitor<String, String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public String visit(NodeList n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if (n.present()) {
         String _ret = null;
         int _count = 0;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            e.nextElement().accept(this, argu);
            _count++;
         }
         return _ret;
      } else
         return null;
   }

   public String visit(NodeOptional n, String argu) {
      if (n.present())
         return n.node.accept(this, argu);
      else
         return null;
   }

   public String visit(NodeSequence n, String argu) {
      String _ret = null;
      int _count = 0;
      for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
         e.nextElement().accept(this, argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) {
      return null;
   }

   public static class TempInterval {
      public String tempId;
      public int firstUse = Integer.MAX_VALUE;
      public int lastUse = Integer.MIN_VALUE;
      public int definition = -1;

      public TempInterval(String tempId) {
         this.tempId = tempId;
      }
   }

   public static class ProcedureIntervals {
      public String procedureName;
      public Map<String, TempInterval> tempIntervals = new HashMap<>();

      public int numParams = 0;
      public int maxCallArgs = 0;

      public ProcedureIntervals(String name) {
         this.procedureName = name;
      }
   }

   public Map<String, ProcedureIntervals> procedureIntervals = new HashMap<>();
   public ProcedureIntervals currProcedure = null;
   public int currPos = 1;

   private Map<String, Integer> labelPositions = new HashMap<>();
   private Map<Integer, Set<String>> jumpTargets = new HashMap<>();
   private boolean inProcedure = false;

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret = null;
      currProcedure = new ProcedureIntervals("MAIN");
      inProcedure = true;
      labelPositions.clear();
      jumpTargets.clear();

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      extendLiveRangesForLoops();

      procedureIntervals.put("MAIN", currProcedure);
      inProcedure = false;

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, String argu) {
      String _ret = null;

      for (Node node : n.f0.nodes) {
         NodeSequence pair = (NodeSequence) node;

         if (pair.elementAt(0) instanceof NodeOptional) {
            NodeOptional opt = (NodeOptional) pair.elementAt(0);
            if (opt.present()) {
               Label labelNode = (Label) opt.node;
               String label = labelNode.f0.toString();
               labelPositions.put(label, currPos + 1);
            }
         }

         pair.elementAt(1).accept(this, argu);
      }

      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public String visit(Procedure n, String argu) {
      String _ret = null;
      String proc = n.f0.accept(this, argu);
      currPos = 1;
      currProcedure = new ProcedureIntervals(proc);
      inProcedure = true;
      labelPositions.clear();
      jumpTargets.clear();

      n.f1.accept(this, argu);
      String str = n.f2.accept(this, argu);
      int params = Integer.parseInt(str);
      currProcedure.numParams = params;

      for (int i = 0; i < params; i++) {
         String t = "TEMP " + i;
         TempInterval ti = new TempInterval(t);
         ti.definition = currPos;
         ti.firstUse = currPos;
         ti.lastUse = currPos;
         currProcedure.tempIntervals.put(t, ti);
      }

      n.f3.accept(this, argu);
      n.f4.accept(this, argu);

      extendLiveRangesForLoops();

      procedureIntervals.put(proc, currProcedure);
      inProcedure = false;
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    * | ErrorStmt()
    * | CJumpStmt()
    * | JumpStmt()
    * | HStoreStmt()
    * | HLoadStmt()
    * | MoveStmt()
    * | PrintStmt()
    */
   public String visit(Stmt n, String argu) {
      String _ret = null;
      currPos++;
      n.f0.accept(this, argu);
      return _ret;
   }

   /** f0 -> "NOOP" */
   public String visit(NoOpStmt n, String argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /** f0 -> "ERROR" */
   public String visit(ErrorStmt n, String argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /** f0 -> "CJUMP" f1 -> Temp() f2 -> Label() */
   public String visit(CJumpStmt n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String label = n.f2.accept(this, argu);
      if (inProcedure) {
         jumpTargets.computeIfAbsent(currPos, k -> new HashSet<>()).add(label);
      }

      return null;
   }

   /** f0 -> "JUMP" f1 -> Label() */
   public String visit(JumpStmt n, String argu) {
      n.f0.accept(this, argu);
      String label = n.f1.accept(this, argu);
      if (inProcedure) {
         jumpTargets.computeIfAbsent(currPos, k -> new HashSet<>()).add(label);
      }

      return null;
   }

   /** f0 -> "HSTORE" f1 -> Temp() f2 -> IntegerLiteral() f3 -> Temp() */
   public String visit(HStoreStmt n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return null;
   }

   /** f0 -> "HLOAD" f1 -> Temp() f2 -> Temp() f3 -> IntegerLiteral() */
   public String visit(HLoadStmt n, String argu) {
      n.f0.accept(this, argu);
      String temp = n.f1.accept(this, argu);
      TempInterval interval = currProcedure.tempIntervals.getOrDefault(temp, new TempInterval(temp));
      interval.definition = currPos;
      interval.firstUse = Math.min(interval.firstUse, currPos);
      interval.lastUse = currPos;
      currProcedure.tempIntervals.put(temp, interval);

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return null;
   }

   /** f0 -> "MOVE" f1 -> Temp() f2 -> Exp() */
   public String visit(MoveStmt n, String argu) {
      n.f0.accept(this, argu);
      String temp = n.f1.accept(this, argu);
      TempInterval interval = currProcedure.tempIntervals.getOrDefault(temp, new TempInterval(temp));
      interval.definition = currPos;
      interval.firstUse = Math.min(interval.firstUse, currPos);
      interval.lastUse = currPos;
      currProcedure.tempIntervals.put(temp, interval);

      n.f2.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return null;
   }

   /** f0 -> Call() | HAllocate() | BinOp() | SimpleExp() */
   public String visit(Exp n, String argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "BEGIN" f1 -> StmtList() f2 -> "RETURN" f3 -> SimpleExp() f4 -> "END"
    */
   public String visit(StmtExp n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public String visit(Call n, String argu) {
      n.f0.accept(this, argu); // "CALL"
      n.f1.accept(this, argu); // function being called
      n.f2.accept(this, argu); // "("

      int argCount = 0;
      if (n.f3.present()) {
         for (Enumeration<Node> e = n.f3.elements(); e.hasMoreElements();) {
            String arg = e.nextElement().accept(this, argu);
            if (arg != null && arg.startsWith("TEMP ")) {
               TempInterval interval = currProcedure.tempIntervals.getOrDefault(arg, new TempInterval(arg));
               interval.firstUse = Math.min(interval.firstUse, currPos);
               interval.lastUse = Math.max(interval.lastUse, currPos);
               currProcedure.tempIntervals.put(arg, interval);
            }
            argCount++;
         }
      }

      currProcedure.maxCallArgs = Math.max(currProcedure.maxCallArgs, argCount);

      n.f4.accept(this, argu);
      return null;
   }

   /** f0 -> "HALLOCATE" f1 -> SimpleExp() */
   public String visit(HAllocate n, String argu) {
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return null;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      n.f0.accept(this, argu);
      String temp = n.f1.accept(this, argu);
      TempInterval interval = currProcedure.tempIntervals.getOrDefault(temp, new TempInterval(temp));
      interval.definition = currPos;
      interval.firstUse = Math.min(interval.firstUse, currPos);
      interval.lastUse = currPos;
      currProcedure.tempIntervals.put(temp, interval);
      n.f2.accept(this, argu);
      return null;
   }

   /** f0 -> "LE" | "NE" | "PLUS" | "MINUS" | "TIMES" | "DIV" */
   public String visit(Operator n, String argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /** f0 -> Temp() | IntegerLiteral() | Label() */
   public String visit(SimpleExp n, String argu) {
      n.f0.accept(this, argu);
      return null;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public String visit(Temp n, String argu) {
      n.f0.accept(this, argu);
      String id = n.f1.accept(this, argu);
      String temp = "TEMP " + id;

      TempInterval interval = currProcedure.tempIntervals.getOrDefault(temp, new TempInterval(temp));
      interval.firstUse = Math.min(interval.firstUse, currPos);
      interval.lastUse = currPos;
      currProcedure.tempIntervals.put(temp, interval);

      return temp;
   }

   /** f0 -> <INTEGER_LITERAL> */
   public String visit(IntegerLiteral n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   /** f0 -> <IDENTIFIER> */
   public String visit(Label n, String argu) {
      n.f0.accept(this, argu);
      return n.f0.toString();
   }

   private static class LoopRegion {
      String label;
      int start;
      int end;

      LoopRegion(String label, int start, int end) {
         this.label = label;
         this.start = start;
         this.end = end;
      }
   }

   private void extendLiveRangesForLoops() {
      if (currProcedure == null)
         return;

      Set<LoopRegion> loops = detectLoops();

      if (loops.isEmpty())
         return;

      for (LoopRegion loop : loops) {
         extendRangesInLoop(loop);
      }
   }

   private Set<LoopRegion> detectLoops() {
      Set<LoopRegion> loops = new HashSet<>();

      for (Map.Entry<Integer, Set<String>> entry : jumpTargets.entrySet()) {
         int jumpPos = entry.getKey();
         for (String targetLabel : entry.getValue()) {
            Integer labelPos = labelPositions.get(targetLabel);
            if (labelPos != null && labelPos <= jumpPos) {
               loops.add(new LoopRegion(targetLabel, labelPos, jumpPos));
            }
         }
      }

      return mergeOverlappingLoops(loops);
   }

   private Set<LoopRegion> mergeOverlappingLoops(Set<LoopRegion> loops) {
      if (loops.size() <= 1)
         return loops;

      List<LoopRegion> sorted = new ArrayList<>(loops);
      sorted.sort(Comparator.comparingInt(l -> l.start));

      Set<LoopRegion> merged = new HashSet<>();
      LoopRegion current = null;

      for (LoopRegion loop : sorted) {
         if (current == null) {
            current = loop;
         } else if (loop.start <= current.end) {
            current = new LoopRegion(
                  current.label,
                  Math.min(current.start, loop.start),
                  Math.max(current.end, loop.end));
         } else {
            merged.add(current);
            current = loop;
         }
      }

      if (current != null) {
         merged.add(current);
      }

      return merged;
   }

   private void extendRangesInLoop(LoopRegion loop) {
      for (TempInterval interval : currProcedure.tempIntervals.values()) {
         boolean usedInLoop = !(interval.lastUse < loop.start || interval.firstUse > loop.end);

         if (usedInLoop) {
            interval.firstUse = Math.min(interval.firstUse, loop.start);
            interval.lastUse = Math.max(interval.lastUse, loop.end);
         }
      }
   }
}